### ISSUE TITLE
modules

### ISSUE THREAD

**Issue by compufox** [GNU-Pony/sweetie-bot#1]
How would these modules be written? Like shell scripts?

Also what if you had, say a .deb file, could you pass it to sweetiebot and it'll spit out a package in the right format?

I wouldn't mind working on this.

**Comment by maandree** [comment]
You can use any language at all, provided that it runs with free software, on GNU/Linux.
If you choose any language other than Bash, if you prefer even with Bash, you need to
add a wrapper script in Bash that has the expected functions.

Sweetie-bot should not specifically support that, but a module is allowed to add that
functionallity. The modules are only required to support crawling and convertions from
Spike scrolls. The crawler should convert found packages at the time they are found.

**Comment by compufox** [comment]
Okay. I was looking at the specs you wrote for Spike scrolls and I'm not sure how sweetie-bot is supposed to handle the pre-built application data in the debs, rpms, and xz's.

**Comment by maandree** [comment]
If is preferable that the converted package are the source for the packages, not built packages.
Say that you are crawling Arch Linux's official repository which contains pre-built packages in form
of .pkg.tar.xz files, instead of converting those files, the PKGBUILD and .install files that are used
to create .pkg.tar.xz files are converted.

If however the pre-built packages are converted, that name of that packages, append by -bin,
is used for the output package name and Spike scroll will have to convert download the pre-built
package from where it is uploaded for the crawled distribution and include instrustions for
installing the files in the package.

For example, if a distribution uses .tar files containing built files and a package metadata
file called PACKAGE, to convert it to a Spike scroll, PACKAGE is parsed and converted
to a Spike scroll which is then filled with the sources field that contains the location of
the .tar files, and a package function that moves all files in srcdir (the .tar file is extracted),
except PACKAGE, to pkgdir.

**Comment by compufox** [comment]
Oh okay so if it can, get a link for the sources but if not then change the scroll name to PACKAGE-bin.scroll and have the source URL pointing to the pre-built package? 

(Just clarifying)

**Comment by maandree** [comment]
Yes.
